### ISSUE TITLE
Cannot create Google Sheets dataset in Superset

### ISSUE THREAD

**Issue by RhysDavis** [betodealmeida/shillelagh#112]
Error adding database from superset with logs below. I'm trying to access the test sheet here https://docs.google.com/spreadsheets/d/1_rN3lm0R_bU3NemO0s9pbFkY5LQPcuy1pscv8ZXPtg8

```
8-23 18:20:31,398:INFO:shillelagh.adapters.api.gsheets.adapter:GET https://docs.google.com/spreadsheets/d/1_rN3lm0R_bU3NemO0s9pbFkY5LQPcuy1pscv8ZXPtg8/gviz/tq?gid=0&tq=SELECT%20%2A%20LIMIT%201
2021-08-23 18:20:31,400:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.google.com:443
2021-08-23 18:20:31,604:DEBUG:urllib3.connectionpool:https://docs.google.com:443 "GET /spreadsheets/d/1_rN3lm0R_bU3NemO0s9pbFkY5LQPcuy1pscv8ZXPtg8/gviz/tq?gid=0&tq=SELECT%20%2A%20LIMIT%201 HTTP/1.1" 200 None
2021-08-23 18:20:31,607:DEBUG:shillelagh.adapters.api.gsheets.adapter:Received payload: {'version': '0.6', 'reqId': '0', 'status': 'ok', 'sig': '1453301915', 'table': {'cols': [{'id': 'A', 'label': 'country', 'type': 'string'}, {'id': 'B', 'label': 'cnt', 'type': 'number', 'pattern': 'General'}], 'rows': [{'c': [{'v': 'BR'}, {'v': 1.0, 'f': '1'}]}], 'parsedNumHeaders': 0}}
2021-08-23 18:20:31,619:WARNING:shillelagh.backends.apsw.db:Couldn't load adapter
2021-08-23 18:20:31,621:WARNING:shillelagh.backends.apsw.db:Couldn't load adapter
()
Traceback (most recent call last):
  File "/app/superset/datasets/commands/create.py", line 51, in run
    dataset.fetch_metadata(commit=False)
  File "/app/superset/connectors/sqla/models.py", line 1502, in fetch_metadata
    new_columns = self.external_metadata()
  File "/app/superset/connectors/sqla/models.py", line 666, in external_metadata
    database=self.database, table_name=self.table_name, schema_name=self.schema,
  File "/app/superset/connectors/sqla/utils.py", line 47, in get_physical_table_metadata
    raise NoSuchTableError
sqlalchemy.exc.NoSuchTableError: ()
2021-08-23 18:20:31,622:WARNING:superset.datasets.commands.create:()
Traceback (most recent call last):
  File "/app/superset/datasets/commands/create.py", line 51, in run
    dataset.fetch_metadata(commit=False)
  File "/app/superset/connectors/sqla/models.py", line 1502, in fetch_metadata
    new_columns = self.external_metadata()
  File "/app/superset/connectors/sqla/models.py", line 666, in external_metadata
    database=self.database, table_name=self.table_name, schema_name=self.schema,
  File "/app/superset/connectors/sqla/utils.py", line 47, in get_physical_table_metadata
    raise NoSuchTableError
sqlalchemy.exc.NoSuchTableError: ()
Error creating model DatasetRestApi: Dataset could not be created.
Traceback (most recent call last):
  File "/app/superset/datasets/commands/create.py", line 51, in run
    dataset.fetch_metadata(commit=False)
  File "/app/superset/connectors/sqla/models.py", line 1502, in fetch_metadata
    new_columns = self.external_metadata()
  File "/app/superset/connectors/sqla/models.py", line 666, in external_metadata
    database=self.database, table_name=self.table_name, schema_name=self.schema,
  File "/app/superset/connectors/sqla/utils.py", line 47, in get_physical_table_metadata
    raise NoSuchTableError
sqlalchemy.exc.NoSuchTableError: ()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/superset/datasets/api.py", line 251, in post
    new_model = CreateDatasetCommand(g.user, item).run()
  File "/app/superset/datasets/commands/create.py", line 65, in run
    raise DatasetCreateFailedError() from ex
superset.datasets.commands.exceptions.DatasetCreateFailedError: Dataset could not be created.
2021-08-23 18:20:31,625:ERROR:superset.datasets.api:Error creating model DatasetRestApi: Dataset could not be created.
Traceback (most recent call last):
  File "/app/superset/datasets/commands/create.py", line 51, in run
    dataset.fetch_metadata(commit=False)
  File "/app/superset/connectors/sqla/models.py", line 1502, in fetch_metadata
    new_columns = self.external_metadata()
  File "/app/superset/connectors/sqla/models.py", line 666, in external_metadata
    database=self.database, table_name=self.table_name, schema_name=self.schema,
  File "/app/superset/connectors/sqla/utils.py", line 47, in get_physical_table_metadata
    raise NoSuchTableError
sqlalchemy.exc.NoSuchTableError: ()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/superset/datasets/api.py", line 251, in post
    new_model = CreateDatasetCommand(g.user, item).run()
  File "/app/superset/datasets/commands/create.py", line 65, in run
    raise DatasetCreateFailedError() from ex
superset.datasets.commands.exceptions.DatasetCreateFailedError: Dataset could not be created.
```

I'm building superset from a Dockerfile that looks like this
```
FROM apache/superset:latest

# Switching to root to install the required packages
USER root

RUN pip install clickhouse-driver==0.2.0
RUN pip install clickhouse-sqlalchemy==0.1.6
RUN pip install shillelagh[gsheetsapi]==1.0.0

# Switching back to using the `superset` user
USER superset
```

**Comment by betodealmeida** [comment]
@RhysDavis did you alter the URL?

The full URL should be "https://docs.google.com/spreadsheets/d/1_rN3lm0R_bU3NemO0s9pbFkY5LQPcuy1pscv8ZXPtg8/edit", with `/edit` in the end.

**Comment by betodealmeida** [comment]
```
% shillelagh
sql> SELECT * FROM "https://docs.google.com/spreadsheets/d/1_rN3lm0R_bU3NemO0s9pbFkY5LQPcuy1pscv8ZXPtg8/edit";
country      cnt
---------  -----
BR             2
BR             4
IN             6
ZA             7
CR            11
sql>
```

**Comment by betodealmeida** [comment]
Oh, I think I hit the same bug in Superset today. I can't create a dataset using `shillelagh` as a database. I'll fix it there.

**Comment by RhysDavis** [comment]
@betodealmeida So I did not edit the URL and used the URL with `/edit` on the end, (just tried another test with a new sheet), and got the same output for the most part:

![image](https://user-images.githubusercontent.com/683108/130512963-1608c867-3cdf-45fe-9c07-976759a5450a.png)

```
2021-08-23 20:10:12,714:INFO:shillelagh.adapters.api.gsheets.adapter:GET https://docs.google.com/spreadsheets/d/1d-SL0oK30-00uKn-noF-f5Kx6IeLqRQCvNs26fpWOHQ/gviz/tq?gid=0&tq=SELECT%20%2A%20LIMIT%201
2021-08-23 20:10:12,717:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): docs.google.com:443
2021-08-23 20:10:12,903:DEBUG:urllib3.connectionpool:https://docs.google.com:443 "GET /spreadsheets/d/1d-SL0oK30-00uKn-noF-f5Kx6IeLqRQCvNs26fpWOHQ/gviz/tq?gid=0&tq=SELECT%20%2A%20LIMIT%201 HTTP/1.1" 200 None
2021-08-23 20:10:12,909:DEBUG:shillelagh.adapters.api.gsheets.adapter:Received payload: {'version': '0.6', 'reqId': '0', 'status': 'ok', 'sig': '712529551', 'table': {'cols': [{'id': 'A', 'label': 'COL_A', 'type': 'number', 'pattern': 'General'}, {'id': 'B', 'label': 'COL_B', 'type': 'number', 'pattern': 'General'}], 'rows': [{'c': [{'v': 23.0, 'f': '23'}, {'v': 4.0, 'f': '4'}]}], 'parsedNumHeaders': 0}}
2021-08-23 20:10:12,929:WARNING:shillelagh.backends.apsw.db:Couldn't load adapter
2021-08-23 20:10:12,932:WARNING:shillelagh.backends.apsw.db:Couldn't load adapter
()
Traceback (most recent call last):
  File "/app/superset/datasets/commands/create.py", line 51, in run
    dataset.fetch_metadata(commit=False)
  File "/app/superset/connectors/sqla/models.py", line 1502, in fetch_metadata
    new_columns = self.external_metadata()
  File "/app/superset/connectors/sqla/models.py", line 666, in external_metadata
    database=self.database, table_name=self.table_name, schema_name=self.schema,
  File "/app/superset/connectors/sqla/utils.py", line 47, in get_physical_table_metadata
    raise NoSuchTableError
sqlalchemy.exc.NoSuchTableError: ()
2021-08-23 20:10:12,934:WARNING:superset.datasets.commands.create:()
Traceback (most recent call last):
  File "/app/superset/datasets/commands/create.py", line 51, in run
    dataset.fetch_metadata(commit=False)
  File "/app/superset/connectors/sqla/models.py", line 1502, in fetch_metadata
    new_columns = self.external_metadata()
  File "/app/superset/connectors/sqla/models.py", line 666, in external_metadata
    database=self.database, table_name=self.table_name, schema_name=self.schema,
  File "/app/superset/connectors/sqla/utils.py", line 47, in get_physical_table_metadata
    raise NoSuchTableError
sqlalchemy.exc.NoSuchTableError: ()
Error creating model DatasetRestApi: Dataset could not be created.
Traceback (most recent call last):
  File "/app/superset/datasets/commands/create.py", line 51, in run
    dataset.fetch_metadata(commit=False)
  File "/app/superset/connectors/sqla/models.py", line 1502, in fetch_metadata
    new_columns = self.external_metadata()
  File "/app/superset/connectors/sqla/models.py", line 666, in external_metadata
    database=self.database, table_name=self.table_name, schema_name=self.schema,
  File "/app/superset/connectors/sqla/utils.py", line 47, in get_physical_table_metadata
    raise NoSuchTableError
sqlalchemy.exc.NoSuchTableError: ()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/superset/datasets/api.py", line 251, in post
    new_model = CreateDatasetCommand(g.user, item).run()
  File "/app/superset/datasets/commands/create.py", line 65, in run
    raise DatasetCreateFailedError() from ex
superset.datasets.commands.exceptions.DatasetCreateFailedError: Dataset could not be created.
2021-08-23 20:10:12,936:ERROR:superset.datasets.api:Error creating model DatasetRestApi: Dataset could not be created.
Traceback (most recent call last):
  File "/app/superset/datasets/commands/create.py", line 51, in run
    dataset.fetch_metadata(commit=False)
  File "/app/superset/connectors/sqla/models.py", line 1502, in fetch_metadata
    new_columns = self.external_metadata()
  File "/app/superset/connectors/sqla/models.py", line 666, in external_metadata
    database=self.database, table_name=self.table_name, schema_name=self.schema,
  File "/app/superset/connectors/sqla/utils.py", line 47, in get_physical_table_metadata
    raise NoSuchTableError
sqlalchemy.exc.NoSuchTableError: ()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/superset/datasets/api.py", line 251, in post
    new_model = CreateDatasetCommand(g.user, item).run()
  File "/app/superset/datasets/commands/create.py", line 65, in run
    raise DatasetCreateFailedError() from ex
superset.datasets.commands.exceptions.DatasetCreateFailedError: Dataset could not be created.
```

**Comment by betodealmeida** [comment]
@RhysDavis can you try installing `shillelagh` 1.0.1 and see it fixes the problem?

**Comment by RhysDavis** [comment]
@betodealmeida 1.0.1 fixes the issue! thank you!
