### ISSUE TITLE
Unable to connect to Shillelagh using SQLAlchemy URI in Superset

### ISSUE THREAD

**Issue by Piyushency** [betodealmeida/shillelagh#243]
I want to use Shillelagh for querying local csv file. Steps followed:
1. pip install "shillelagh"
2. Even installed using $ pip install https://github.com/rogerbinns/apsw/releases/download/3.38.1-r1/apsw-3.38.1-r1.zip \
--global-option=fetch --global-option=--version --global-option=3.38.1 --global-option=--all \
--global-option=build --global-option=--enable-all-extensions
3. Have already deployed Superset and when trying to connect a new database, entering sqlalchemy uri as "shillelagh://" and clicking on connect gives out an error: 
An error occurred while creating databases: (sqlalchemy_uri) APSWDialect cannot be used as a data source for security reasons.

Have already tried changing config.py to PREVENT_UNSAFE_DB_CONNECTIONS = False, still it gives out the same error

On Terminal:
gsheets works on terminal. But when trying to use it for querying csv
sql>SELECT * FROM "tips.csv";
I get below errors:

`Unhandled exception in event loop:
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/piyush/.local/lib/python3.8/site-packages/prompt_toolkit/input/vt100.py", line 173, in callback_wrapper
    callback()
  File "/home/piyush/.local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 710, in read_from_input
    self.key_processor.process_keys()
  File "/home/piyush/.local/lib/python3.8/site-packages/prompt_toolkit/key_binding/key_processor.py", line 270, in process_keys
    self._process_coroutine.send(key_press)
  File "/home/piyush/.local/lib/python3.8/site-packages/prompt_toolkit/key_binding/key_processor.py", line 185, in _process
    self._call_handler(matches[-1], key_sequence=buffer[:])
  File "/home/piyush/.local/lib/python3.8/site-packages/prompt_toolkit/key_binding/key_processor.py", line 320, in _call_handler
    handler.call(event)
  File "/home/piyush/.local/lib/python3.8/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 124, in call
    result = self.handler(event)
  File "/home/piyush/.local/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 807, in _accept_input
    self.default_buffer.validate_and_handle()
  File "/home/piyush/.local/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1877, in validate_and_handle
    self.append_to_history()
  File "/home/piyush/.local/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1385, in append_to_history
    self.history.append_string(self.text)
  File "/home/piyush/.local/lib/python3.8/site-packages/prompt_toolkit/history.py", line 74, in append_string
    self.store_string(string)
  File "/home/piyush/.local/lib/python3.8/site-packages/prompt_toolkit/history.py", line 294, in store_string
    with open(self.filename, "ab") as f:

Exception [Errno 2] No such file or directory: '/home/piyush/.config/shillelagh/shillelagh.history'
Press ENTER to continue...Traceback (most recent call last):
  File "/home/piyush/.local/lib/python3.8/site-packages/shillelagh/backends/apsw/db.py", line 220, in execute
    self._cursor.execute(operation, parameters)
apsw.SQLError: SQLError: no such table: /home/piyush/Downloads/tips.csv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/piyush/.local/bin/shillelagh", line 8, in <module>
    sys.exit(main())
  File "/home/piyush/.local/lib/python3.8/site-packages/shillelagh/console.py", line 210, in main
    cursor.execute(sql)
  File "/home/piyush/.local/lib/python3.8/site-packages/shillelagh/backends/apsw/db.py", line 81, in wrapper
    return method(self, *args, **kwargs)
  File "/home/piyush/.local/lib/python3.8/site-packages/shillelagh/backends/apsw/db.py", line 231, in execute
    self._create_table(uri)
  File "/home/piyush/.local/lib/python3.8/site-packages/shillelagh/backends/apsw/db.py", line 271, in _create_table
    self._cursor.execute(
  File "/home/piyush/.local/lib/python3.8/site-packages/shillelagh/backends/apsw/vt.py", line 244, in Create
    adapter = self.adapter(*deserialized_args)
  File "/home/piyush/.local/lib/python3.8/site-packages/shillelagh/adapters/file/csvfile.py", line 106, in __init__
    column_names = next(reader)
ValueError: could not convert string to float: 'total_bill'`

**Comment by betodealmeida** [comment]
> 3. Have already deployed Superset and when trying to connect a new database, entering sqlalchemy uri as "shillelagh://" and clicking on connect gives out an error:
>        An error occurred while creating databases: (sqlalchemy_uri) APSWDialect cannot be used as a data source for security reasons.
> 
> Have already tried changing config.py to PREVENT_UNSAFE_DB_CONNECTIONS = False, still it gives out the same error

This is unexpected. Did you set this in your `superset_config.py` and restart Superset after changing it?

>  ValueError: could not convert string to float: 'total_bill'`

The problem here is that the CSV adapter uses the `csv.QUOTE_NONNUMERIC` quoting, so all strings **must** be quoted. Your file should look like this:

```csv
"foo","bar"
1,2
```

I know traditionally CSV files are not quoted, but when they're not quoted it's much more expensive to infer the column types, since need to try to cast all the values:

https://github.com/betodealmeida/shillelagh/blob/10d6608adcb2a64e2e9ae7da85239bc17aa53a2c/src/shillelagh/lib.py#L162-L174

**Comment by Piyushency** [comment]
The issue has been resolved for connecting to shillelagh://.
Reinstalling superset through setup.py worked to force the changes made in config.py file.
