### ISSUE TITLE
Cannot create Google Sheets dataset in Superset

### ISSUE THREAD

**Issue by CharlesYe8848** [betodealmeida/shillelagh#323]
<img width="592" alt="image" src="https://user-images.githubusercontent.com/26808857/212447828-cd2e5f54-84aa-4469-8b29-9f5095f5c2ef.png">

Error adding database from superset
apache-superset        2.0.1
shillelagh             1.1.5

2023-01-14 11:01:45,456:WARNING:superset.views.base:SupersetErrorsException
Traceback (most recent call last):
  File "/root/superset_venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/superset_venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/root/superset_venv/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 89, in wraps
    return f(self, *args, **kwargs)
  File "/root/superset_venv/lib/python3.9/site-packages/superset/views/base_api.py", line 113, in wraps
    raise ex
  File "/root/superset_venv/lib/python3.9/site-packages/superset/views/base_api.py", line 110, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/root/superset_venv/lib/python3.9/site-packages/superset/utils/core.py", line 1524, in time_function
    response = func(*args, **kwargs)
  File "/root/superset_venv/lib/python3.9/site-packages/superset/utils/log.py", line 245, in wrapper
    value = f(*args, **kwargs)
  File "/root/superset_venv/lib/python3.9/site-packages/superset/views/base_api.py", line 83, in wraps
    return f(self, *args, **kwargs)
  File "/root/superset_venv/lib/python3.9/site-packages/superset/databases/api.py", line 1183, in validate_parameters
    command.run()
  File "/root/superset_venv/lib/python3.9/site-packages/superset/databases/commands/validate.py", line 96, in run
    raise InvalidParametersError(errors)
superset.databases.commands.exceptions.InvalidParametersError: [SupersetError(message='The URL could not be identified. Please check for typos and make sure that ‘Type of Google Sheets allowed’ selection matches the input.', error_type=<SupersetErrorType.TABLE_DOES_NOT_EXIST_ERROR: 'TABLE_DOES_NOT_EXIST_ERROR'>, level=<ErrorLevel.WARNING: 'warning'>, extra={'catalog': {'idx': 0, 'url': True}, 'issue_codes': [{'code': 1003, 'message': 'Issue 1003 - There is a syntax error in the SQL query. Perhaps there was a misspelling or a typo.'}, {'code': 1005, 'message': 'Issue 1005 - The table was deleted or renamed in the database.'}]})]
2023-01-14 11:01:45,457:INFO:werkzeug:183.94.173.5 - - [14/Jan/2023 11:01:45] "POST /api/v1/database/validate_parameters HTTP/1.1" 422 -

when i try install shillelagh[gsheetsapi]==1.0.1 and  it doesn't work?

https://github.com/betodealmeida/shillelagh/issues/112

**Comment by betodealmeida** [comment]
Hi, @CharlesYe8848! What's the URL for the sheet? Are you sure it's public?

**Comment by betodealmeida** [comment]
@CharlesYe8848 feel free to reopen this.

**Comment by CharlesYe8848** [comment]
您好，你发的邮件我已收到。
