### ISSUE TITLE
Issue with shillelagh Dialect on superset master

### ISSUE THREAD

**Issue by cancan101** [betodealmeida/shillelagh#375]
Using the shillelagh Dialect with Superset 1.5.1 works fine. Upgrading to master is leading to an error here once the schema is selected:
![image](https://github.com/betodealmeida/shillelagh/assets/51059/c48abfd3-9aca-42fc-a9f2-57cf263b3b97)
```
2023-07-24 18:29:43,727:WARNING:superset.views.base:HTTPException
Traceback (most recent call last):
  File "/Users/alex/.pyenv/versions/3.9.8/envs/superset-dev8/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/alex/.pyenv/versions/3.9.8/envs/superset-dev8/lib/python3.9/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/alex/.pyenv/versions/3.9.8/envs/superset-dev8/lib/python3.9/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/Users/alex/.pyenv/versions/3.9.8/envs/superset-dev8/lib/python3.9/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/alex/.pyenv/versions/3.9.8/envs/superset-dev8/lib/python3.9/site-packages/werkzeug/routing/map.py", line 652, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-07-24 18:29:43,728:INFO:werkzeug:127.0.0.1 - - [24/Jul/2023 18:29:43] "GET /superset/tables/2/main/undefined/false/ HTTP/1.1" 404 -
```

I am not sure how / why is is formulating that URL. I assume there is some method that the dialect needs to expose that is not correctly being exposed.

**Comment by cancan101** [comment]
looks like I forgot to rebuild front end assets.
