### ISSUE TITLE
Installing without all dependencies can lead to CLI import errors

### ISSUE THREAD

**Issue by cwaldbieser** [betodealmeida/shillelagh#400]
**Describe the bug**
If I install only the AWS S3 dependencies rather than `[all]`, then the CLI fails with an error.

**To Reproduce**
1. pip install shillelagh
2. pip install 'shillelagh[s3selectapi]'
3. shillelagh
```
Traceback (most recent call last):
  File "/home/waldbiec/.virtualenvs/shillelagh-py3.10/bin/shillelagh", line 5, in <module>
    from shillelagh.console import main
  File "/home/waldbiec/.virtualenvs/shillelagh-py3.10/lib/python3.10/site-packages/shillelagh/console.py", line 27, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Expected behavior**
I expected to enter the REPL.

**Desktop (please complete the following information):**
 - OS: Ubutu Linux 22.04
 - Python 3.10

**Additional context**
If I manually install PyYaml, I get another import error:

```
Traceback (most recent call last):
  File "/home/waldbiec/.virtualenvs/shillelagh-py3.10/bin/shillelagh", line 5, in <module>
    from shillelagh.console import main
  File "/home/waldbiec/.virtualenvs/shillelagh-py3.10/lib/python3.10/site-packages/shillelagh/console.py", line 28, in <module>
    from appdirs import user_config_dir
ModuleNotFoundError: No module named 'appdirs'
```

If I install with all adapters, the CLI works as expected.

**Comment by cwegener** [comment]
Thanks for pointing this out.

The actual error is slightly different though.

The installation for the CLi is actually `pip install 'shillelagh[console]'` which then results in the missing dependency for `requests-cache`

```
shillelagh
Traceback (most recent call last):
  File "/tmp/venv/bin/shillelagh", line 5, in <module>
    from shillelagh.console import main
  File "/tmp/venv/lib/python3.10/site-packages/shillelagh/console.py", line 38, in <module>
    from shillelagh.backends.apsw.db import connect
  File "/tmp/venv/lib/python3.10/site-packages/shillelagh/backends/apsw/db.py", line 25, in <module>
    from shillelagh import functions
  File "/tmp/venv/lib/python3.10/site-packages/shillelagh/functions.py", line 10, in <module>
    from shillelagh.lib import find_adapter
  File "/tmp/venv/lib/python3.10/site-packages/shillelagh/lib.py", line 24, in <module>
    import requests_cache
ModuleNotFoundError: No module named 'requests_cache'
```
