### ISSUE TITLE
No module named 'jsonpath'

### ISSUE THREAD

**Issue by thomas-michels** [betodealmeida/shillelagh#448]
**Describe the bug**
I trying to connect superset in an API using Shillelagh, but when I do the configuration bellow superset returns that error.

![image](https://github.com/betodealmeida/shillelagh/assets/57485730/d7b1aa8f-49c2-4d96-8584-f1933a681f40)

ERROR: (builtins.NoneType) None
[SQL: (shillelagh.exceptions.InterfaceError) Unable to load adapter genericjsonapi
(Background on this error at: https://sqlalche.me/e/14/rvf5)]
(Background on this error at: https://sqlalche.me/e/14/dbapi)

**Database Configuration**
SQLALCHEMY URI: shillelagh+safe://localhost:8000
ENGINE PARAMETERS: {"connect_args":{"adapters":["genericjsonapi"],"adapter_kwargs":{"genericjsonapi":{"x-token-user":"XXX","x-token-user-id":"123"}}}}

**Expected behavior**
Superset connects with success in an API.

**Screenshots**
Error found in logs
![image](https://github.com/betodealmeida/shillelagh/assets/57485730/3d4bfefd-f9fc-47d6-8abe-46f986f91294)
![image](https://github.com/betodealmeida/shillelagh/assets/57485730/92353b66-a9f2-46ba-84b9-f3e00c06c821)

**Desktop (please complete the following information):**
 - Docker - [Image version ](https://hub.docker.com/layers/apache/superset/latest/images/sha256-c284038dc19cb67bfcd34b6729f112cdc3cca6805daa310f8be362a6f628b2ce?context=explore)

**Comment by betodealmeida** [comment]
@thomas-michels this can be fixed by running:

```bash
$ pip install python-jsonpath
```

How did you install `shillelagh`? If you're using the Generic JSON adapter you should install it:

```bash
$ pip install 'shillelagh[genericjsonapi]'
```

Which should install the JSON path library.

**Comment by thomas-michels** [comment]
@betodealmeida I used `pip install 'shillelagh[all]'`, using `pip install python-jsonpath` I had the same problem

**Comment by betodealmeida** [comment]
@thomas-michels did you run the commands inside the Docker image? On the latest version of shillelagh running `pip install 'shillelagh[all]'` will install `python-jsonpath`:

https://github.com/betodealmeida/shillelagh/blob/70a60df577726546ca7c38e7a613c929df39b8ac/setup.cfg#L116

**Comment by betodealmeida** [comment]
Closing this, feel free to reopen if the issue persists.

**Comment by RoffyMonsta** [comment]
Hey @betodealmeida i've just cloned https://github.com/apache/superset and i'm getting the same error when trying to test the connection with generic json api. Can you please help me? 

```
superset_app          | 2024-10-09 15:38:21,695:DEBUG:superset.stats_logger:[stats_logger] (incr) test_connection_attempt
superset_app          | 2024-10-09 15:38:21,711:DEBUG:superset.models.core:Database._get_sqla_engine(). Masked URL: shillelagh+safe://
superset_app          | 2024-10-09 15:38:21,736:WARNING:shillelagh.adapters.registry:Couldn't load adapter genericjsonapi
superset_app          | 2024-10-09 15:38:21,736:DEBUG:shillelagh.adapters.registry:No module named 'jsonpath'
superset_app          | 2024-10-09 15:38:21,737:DEBUG:superset.stats_logger:[stats_logger] (incr) test_connection_error.DBAPIError
superset_app          | 2024-10-09 15:38:21,744:DEBUG:superset.stats_logger:[stats_logger] (incr) DatabaseRestApi.test_connection.error
superset_app          | 2024-10-09 15:38:21,744:WARNING:superset.views.base:SupersetErrorsException
superset_app          | Traceback (most recent call last):
superset_app          |   File "/app/superset/commands/database/test_connection.py", line 171, in run
superset_app          |     raise DBAPIError(ex_str or None, None, None)
superset_app          | sqlalchemy.exc.DBAPIError: (builtins.NoneType) None
superset_app          | [SQL: (shillelagh.exceptions.InterfaceError) Unable to load adapter genericjsonapi
superset_app          | (Background on this error at: https://sqlalche.me/e/14/rvf5)]
superset_app          | (Background on this error at: https://sqlalche.me/e/14/dbapi)
superset_app          |
superset_app          | The above exception was the direct cause of the following exception:
superset_app          |
superset_app          | Traceback (most recent call last):
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
superset_app          |     rv = self.dispatch_request()
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
superset_app          |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
superset_app          |   File "/usr/local/lib/python3.10/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
superset_app          |     return f(self, *args, **kwargs)
superset_app          |   File "/app/superset/views/base_api.py", line 127, in wraps
superset_app          |     raise ex
superset_app          |   File "/app/superset/views/base_api.py", line 121, in wraps
superset_app          |     duration, response = time_function(f, self, *args, **kwargs)
superset_app          |   File "/app/superset/utils/core.py", line 1470, in time_function
superset_app          |     response = func(*args, **kwargs)
superset_app          |   File "/app/superset/utils/log.py", line 255, in wrapper
superset_app          |     value = f(*args, **kwargs)
superset_app          |   File "/app/superset/views/base_api.py", line 93, in wraps
superset_app          |     return f(self, *args, **kwargs)
superset_app          |   File "/app/superset/databases/api.py", line 920, in test_connection
superset_app          |     TestConnectionDatabaseCommand(item).run()
superset_app          |   File "/app/superset/commands/database/test_connection.py", line 200, in run
superset_app          |     raise SupersetErrorsException(errors) from ex
superset_app          | superset.exceptions.SupersetErrorsException: [SupersetError(message='(builtins.NoneType) None\n[SQL: (shillelagh.exceptions.InterfaceError) Unable to load adapter genericjsonapi\n(Background on this error at: https://sqlalche.me/e/14/rvf5)]\n(Background on this error at: https://sqlalche.me/e/14/dbapi)', error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Shillelagh', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
```
