### ISSUE TITLE
google spreadsheets ProgrammingError: no such table . gsheetsapi

### ISSUE THREAD

**Issue by zshimanchik** [betodealmeida/shillelagh#494]
**Describe the bug**
Latest version of shillelagh doesn't work with google spreadsheets complaining on "shillelagh.exceptions.ProgrammingError: no such table"

**To Reproduce**
1. poetry env use 3.11
2. poetry add "shillelagh[gsheetsapi]"
3. Run the minimalist code
```python
from shillelagh.backends.apsw.db import connect

token = "REAL_WORKING_TOKEN"
connection = connect(":memory:", adapter_kwargs={"gsheetsapi": {"access_token": token}})

cursor = connection.cursor()
sql = 'SELECT * FROM "https://docs.google.com/spreadsheets/d/1_rN3lm0R_bU3NemO0s9pbFkY5LQPcuy1pscv8ZXPtg8/edit#gid=0" LIMIT 1'
print(cursor.execute(sql))
print(cursor.fetchall())
```
4. see error:
```
Traceback (most recent call last):
  File "/Users/zak/Library/Caches/pypoetry/virtualenvs/shillebug-rn9HSb7j-py3.11/lib/python3.11/site-packages/shillelagh/backends/apsw/db.py", line 247, in execute
    self._cursor.execute(operation, parameters)
  File "src/cursor.c", line 970, in APSWCursor_execute.sqlite3_prepare_v3
apsw.SQLError: no such table: https://docs.google.com/spreadsheets/d/1_rN3lm0R_bU3NemO0s9pbFkY5LQPcuy1pscv8ZXPtg8/edit#gid=0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zak/projects/shillebug/justit.py", line 9, in <module>
    print(cursor.execute(sql))
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/zak/Library/Caches/pypoetry/virtualenvs/shillebug-rn9HSb7j-py3.11/lib/python3.11/site-packages/shillelagh/backends/apsw/db.py", line 101, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zak/Library/Caches/pypoetry/virtualenvs/shillebug-rn9HSb7j-py3.11/lib/python3.11/site-packages/shillelagh/backends/apsw/db.py", line 254, in execute
    raise ProgrammingError(message) from ex
shillelagh.exceptions.ProgrammingError: no such table: https://docs.google.com/spreadsheets/d/1_rN3lm0R_bU3NemO0s9pbFkY5LQPcuy1pscv8ZXPtg8/edit#gid=0
```

**Expected behavior**
It works OR It shows relevant error.

**pip freeze**
```
apsw==3.47.1.0
attrs==24.2.0
cachetools==5.5.0
cattrs==24.1.2
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.4.0
cryptography==44.0.0
google-auth==2.36.0
greenlet==3.1.1
idna==3.10
packaging==24.2
platformdirs==4.3.6
pyasn1==0.6.1
pyasn1_modules==0.4.1
pycparser==2.22
pyOpenSSL==24.3.0
python-dateutil==2.9.0.post0
requests==2.32.3
requests-cache==1.2.1
rsa==4.9
shillelagh==1.3.2
six==1.16.0
SQLAlchemy==2.0.36
typing_extensions==4.12.2
url-normalize==1.4.3
urllib3==2.2.3
```

**Way to workaround**
Downgrade apsw from 3.47.1.0 to 3.46.0.1

So this is working pyproject piece:
```yaml
[tool.poetry.dependencies]
python = "^3.11"
apsw = "3.46.0.1"
shillelagh = {extras = ["gsheetsapi"], version = "^1.3.2"}
```

**Comment by betodealmeida** [comment]
This should be fixed in 1.3.3 — newer versions of apsw changes how the "no such table" error message is prefixed, causing this error.
