### ISSUE TITLE
Example csvfile.py initialises weatherapi

### ISSUE THREAD

**Issue by twareing** [betodealmeida/shillelagh#7]
Attempting to run csvfile.py produces the following trace:
```$ python csvfile.py
Traceback (most recent call last):
  File "csvfile.py", line 4, in <module>
    connection = connect(":memory:")
  File "/home/tommy/transfer/lib/python3.8/site-packages/shillelagh/backends/apsw/db.py", line 363, in connect
    enabled_adapters = [
  File "/home/tommy/transfer/lib/python3.8/site-packages/shillelagh/backends/apsw/db.py", line 364, in <listcomp>
    adapter.load()
  File "/home/tommy/transfer/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/tommy/transfer/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/tommy/transfer/lib/python3.8/site-packages/shillelagh/adapters/api/weatherapi.py", line 11, in <module>
    import requests_cache
ModuleNotFoundError: No module named 'requests_cache'
```
installing requests_cache via pip resolves this, but then the csv test generates a cache file:
```$ ls -ltr
-rw-rw-r-- 1 tommy tommy    977 Mar 19 12:05 csvfile.py
-rw-rw-r-- 1 tommy tommy    133 Mar 19 12:06 test.csv
$ python csvfile.py
...
$ ls -ltr
-rw-rw-r-- 1 tommy tommy    977 Mar 19 12:05 csvfile.py
-rw-r--r-- 1 tommy tommy  20480 Mar 19 12:15 weatherapi_cache.sqlite
-rw-rw-r-- 1 tommy tommy    133 Mar 19 12:15 test.csv
```

**Comment by twareing** [comment]
I've now found the docstr on the connect function, and realised that I can pass just the adapter names I want initialised. Thus:
`connection = connect(":memory:", "csvfile")`

or, for my specific use case, by passing an extra adapters parameter to SQLAlechemy's create_engine call:
`engine = create_engine('shillelagh://', adapters='csvfile')`
